<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <groupId>io.github.melin.flink.rest.FlinkClientTest.client</groupId>
    <artifactId>flink-rest-client</artifactId>
    <version>1.0.4</version>
    <packaging>jar</packaging>
    <description>Java library for managing Apache Flink via the Monitoring REST API</description>

    <properties>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <maven.compiler.source>1.8</maven.compiler.source>
        <maven.compiler.target>1.8</maven.compiler.target>
        <project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>

        <junit5jupiter.version>5.9.3</junit5jupiter.version>
        <junit5platform.version>1.9.3</junit5platform.version>
        <assertj.version>3.21.0</assertj.version>
        <spring.version>5.3.29</spring.version>
        <jackson.version>2.15.2</jackson.version>
        <mockito.version>4.0.0</mockito.version>
        <awaitility.version>4.2.0</awaitility.version>
        <javax.annotation-api.version>1.3.2</javax.annotation-api.version>
        <swagger-annotations.version>2.2.15</swagger-annotations.version>
    </properties>
    <dependencies>
        <dependency>
            <groupId>io.swagger.core.v3</groupId>
            <artifactId>swagger-annotations</artifactId>
            <version>${swagger-annotations.version}</version>
        </dependency>
        <dependency>
            <groupId>org.springframework</groupId>
            <artifactId>spring-context</artifactId>
            <version>${spring.version}</version>
        </dependency>
        <dependency>
            <groupId>org.springframework</groupId>
            <artifactId>spring-webmvc</artifactId>
            <version>${spring.version}</version>
        </dependency>
        <dependency>
            <groupId>com.fasterxml.jackson.core</groupId>
            <artifactId>jackson-core</artifactId>
            <version>${jackson.version}</version>
        </dependency>
        <dependency>
            <groupId>com.fasterxml.jackson.core</groupId>
            <artifactId>jackson-databind</artifactId>
            <version>${jackson.version}</version>
        </dependency>
        <dependency>
            <groupId>com.fasterxml.jackson.core</groupId>
            <artifactId>jackson-annotations</artifactId>
            <version>${jackson.version}</version>
        </dependency>

        <dependency>
            <groupId>javax.annotation</groupId>
            <artifactId>javax.annotation-api</artifactId>
            <version>${javax.annotation-api.version}</version>
        </dependency>
        <dependency>
            <groupId>org.junit.jupiter</groupId>
            <artifactId>junit-jupiter-engine</artifactId>
            <version>${junit5jupiter.version}</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.junit.platform</groupId>
            <artifactId>junit-platform-runner</artifactId>
            <version>${junit5platform.version}</version>
            <scope>test</scope>
        </dependency>
    </dependencies>
    <build>
        <sourceDirectory>src/main/java</sourceDirectory>
        <testSourceDirectory>src/test/java</testSourceDirectory>
        <plugins>
            <plugin>
                <groupId>org.codehaus.mojo</groupId>
                <artifactId>build-helper-maven-plugin</artifactId>
                <executions>
                    <execution>
                        <id>add_sources</id>
                        <phase>generate-sources</phase>
                        <goals>
                            <goal>add-source</goal>
                        </goals>
                        <configuration>
                            <sources>
                                <source>${project.build.directory}/generated-sources/swagger/src/main/java</source>
                            </sources>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-source-plugin</artifactId>
                <executions>
                    <execution>
                        <id>attach-sources</id>
                        <goals>
                            <goal>jar</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-javadoc-plugin</artifactId>
                <executions>
                    <execution>
                        <id>attach-javadocs</id>
                        <goals>
                            <goal>jar</goal>
                        </goals>
                        <configuration>
                            <failOnError>false</failOnError>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
            </plugin>
            <plugin>
                <groupId>io.swagger.codegen.v3</groupId>
                <artifactId>swagger-codegen-maven-plugin</artifactId>
                <executions>
                    <execution>
                        <goals>
                            <goal>generate</goal>
                        </goals>
                        <configuration>
                            <inputSpec>${project.basedir}/flink-openapi.yaml</inputSpec>
                            <library>resttemplate</library>
                            <language>java</language>
                            <invokerPackage>io.github.melin.flink.rest.FlinkClientTest.api</invokerPackage>
                            <modelPackage>io.github.melin.flink.rest.FlinkClientTest.model</modelPackage>
                            <apiPackage>io.github.melin.flink.rest.FlinkClientTest.api</apiPackage>
                            <generateApiTests>false</generateApiTests>
                            <generateModelTests>false</generateModelTests>
                            <generateApiDocumentation>false</generateApiDocumentation>
                            <generateModelDocumentation>false</generateModelDocumentation>
                            <generateSupportingFiles>true</generateSupportingFiles>
                            <supportingFilesToGenerate>ApiClient.java,ApiException.java,ApiResponse.java,ApiCallback.java,Authentication.java,JSON.java,Pair.java,Configuration.java,ProgressRequestBody.java,ProgressResponseBody.java,HttpBasicAuth.java,ApiKeyAuth.java,OAuth.java,StringUtil.java,RFC3339DateFormat.java</supportingFilesToGenerate>
                            <configOptions>
                                <hideGenerationTimestamp>false</hideGenerationTimestamp>
                                <sourceFolder>src/main/java</sourceFolder>
                                <java8>true</java8>
                                <dateLibrary>java8</dateLibrary>
                                <singleContentTypes>true</singleContentTypes>
                                <interfaceOnly>true</interfaceOnly>
                            </configOptions>
                            <output>${project.build.directory}/generated-sources/swagger</output>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
            <plugin>
                <groupId>io.fabric8</groupId>
                <artifactId>docker-maven-plugin</artifactId>
                <configuration>
                </configuration>
                <executions>
                    <execution>
                        <id>start-integration-test</id>
                        <phase>pre-integration-test</phase>
                        <goals>
                            <goal>start</goal>
                        </goals>
                        <configuration>
                            <showLogs>false</showLogs>
                            <images>
                                <image>
                                    <name>flink:1.17.1</name>
                                    <alias>flink-jobmanager</alias>
                                    <run>
                                        <ports>
                                            <port>8081:8081</port>
                                            <port>6123</port>
                                            <port>6124</port>
                                            <port>6125</port>
                                        </ports>
                                        <cmd>
                                            <exec>jobmanager</exec>
                                        </cmd>
                                        <env>
                                            <FLINK_JM_MAX_HEAP>512</FLINK_JM_MAX_HEAP>
                                            <FLINK_TM_MAX_HEAP>1024</FLINK_TM_MAX_HEAP>
                                            <JOB_MANAGER_RPC_ADDRESS>flink-jobmanager</JOB_MANAGER_RPC_ADDRESS>
                                        </env>
                                        <network>
                                            <mode>custom</mode>
                                            <name>flink-test</name>
                                            <alias>flink-jobmanager</alias>
                                        </network>
                                        <wait>
                                            <log>Rest endpoint listening at flink-jobmanager:8081</log>
                                            <time>180000</time>
                                        </wait>
                                    </run>
                                </image>
                                <image>
                                    <name>flink:1.17.1</name>
                                    <alias>flink-taskmanager</alias>
                                    <run>
                                        <cmd>
                                            <exec>taskmanager</exec>
                                        </cmd>
                                        <env>
                                            <FLINK_JM_MAX_HEAP>512</FLINK_JM_MAX_HEAP>
                                            <FLINK_TM_MAX_HEAP>1024</FLINK_TM_MAX_HEAP>
                                            <JOB_MANAGER_RPC_ADDRESS>flink-jobmanager</JOB_MANAGER_RPC_ADDRESS>
                                            <TASK_MANAGER_NUMBER_OF_TASK_SLOTS>2</TASK_MANAGER_NUMBER_OF_TASK_SLOTS>
                                        </env>
                                        <network>
                                            <mode>custom</mode>
                                            <name>flink-test</name>
                                            <alias>flink-taskmanager</alias>
                                        </network>
                                        <wait>
                                            <log>Successful registration</log>
                                            <time>180000</time>
                                        </wait>
                                    </run>
                                </image>
                            </images>
                        </configuration>
                    </execution>
                    <execution>
                        <id>stop-integration-test</id>
                        <phase>post-integration-test</phase>
                        <goals>
                            <goal>stop</goal>
                        </goals>
                        <configuration>
                            <images>
                                <image>
                                    <name>flink:1.17.1</name>
                                    <alias>flink-taskmanager</alias>
                                </image>
                                <image>
                                    <name>flink:1.17.1</name>
                                    <alias>flink-jobmanager</alias>
                                </image>
                            </images>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>
</project>
